import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="grid min-h-screen grid-rows-[auto,1fr,auto] px-4 container m-auto">
        <header className='leading-[60px] font-bold'>Kin + StudyCases</header>
        <main className='py-12'>{children}</main>
        <footer className="text-center leading-[60px] opacity-80 ">Con amor</footer>
      </body>
    </html>
  )
}
