import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Foteer from '../components/footer/Footer'
import  Navbar from '../components/navbar/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'StudyCases News',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex min-h-screen flex-col bg-[#121212]">
        <Navbar />

        {/* <header className='leading-[60px] font-bold'>StudyCases News</header> */}
        <main className='grid min-h-screen grid-rows-[auto,1fr,auto] px-4 container m-auto py-24'>{children}</main>
        <Foteer/>
      </body>
    </html>
  )
}
